lib/memories_web/router.ex
defmodule MemoriesWeb.Router do
  use MemoriesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MemoriesWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", MemoriesWeb do
    pipe_through :browser

    get("/login", AlbumAuthenticationController, :index)
    post("/login", AlbumAuthenticationController, :create)

    live("/:album_name", AlbumLive)
    live("/:album_name/:album_order", AlbumLive)
  end

  # Other scopes may use custom stacks.
  # scope "/api", MemoriesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MemoriesWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/memories_web/controllers/album_authentication_controller.ex
defmodule MemoriesWeb.AlbumAuthenticationController do
  require Logger
  use MemoriesWeb, :controller

  alias Memories.Albums

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def create(conn, %{"key" => album_key}) do
    case Albums.get_album(album_key) do
      {:error, _error_message} ->
        conn |> redirect(to: "/login")

      {:ok, album} ->
        conn
        |> put_session(:album_key, album.key)
        |> redirect(to: Routes.live_path(conn, MemoriesWeb.AlbumLive, album.prefix))
    end
  end
end

lib/memories_web/views/album_authentication_view.ex
defmodule MemoriesWeb.AlbumAuthenticationView do
  use MemoriesWeb, :view
end

lib/memories_web/templates/album_authentication/index.html.heex
<div class="w-screen h-screen">
  <div class="flex justify-center items-center w-full h-full flex-row">
    <div class="w-1/4">
      <%= form_for @conn, Routes.album_authentication_path(@conn, :create), fn f -> %>
        <div class="flex flex-row border-2 border-grey-200 rounded p-4 w-full">
          <%= text_input f, :key, class: "grow", placeholder: "Album password" %>
          <%= submit do %>
            <svg class="w-6 h-6 dark:text-white grow-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 9l3 3m0 0l-3 3m3-3H8m13 0a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>